# Generated by Django 4.0.4 on 2022-05-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_title_video_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
    ]
