# Generated by Django 4.0.4 on 2022-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_name_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_idv',
            new_name='video_id',
        ),
    ]
