# Generated by Django 4.0.4 on 2022-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_delete_videoproxy_videoallproxy_videopublishedproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'DRAFT')], default='DR', max_length=2),
        ),
    ]
