# Generated by Django 4.0.4 on 2022-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PU', 'Publish'), ('DR', 'DRAFT')], default='DR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAllProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All Image',
                'verbose_name_plural': 'All Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('images.image',),
        ),
        migrations.CreateModel(
            name='ImagePublishedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published Image',
                'verbose_name_plural': 'Published Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('images.image',),
        ),
    ]
